"""initial schema

Revision ID: 0001_initial_schema
Revises: 0000_required_extensions
Create Date: 2026-09-28 21:07:55.909361

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Tipos propios del proyecto. El autogenere los renderiza con su ruta completa
# (`app.db.types.UtcDateTime`) porque no son de la libreria, asi que la migracion
# necesita poder resolver ese nombre.
import app.db.types

from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
# Antes era `None`. Pasa a colgar de `0000_required_extensions`, que crea `citext`,
# `btree_gist` y `pgcrypto`: sin ellas esta migracion no aplica sobre una base
# nueva, y una base ya migrada no se entera porque no vuelve a correr.
#
# Insertar una revision antes de la primera no altera las bases existentes: la de
# desarrollo esta sellada en `0011` y Alembic solo busca lo que falta.
down_revision: str | None = "0000_required_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Tipos enum del esquema. Copia congelada, no import de `app.models.sql_types`.
#:
#: Esta lista existe por una razon concreta: el autogenere emite los enums *dentro*
#: de cada `create_table` como `sa.Enum(...)`, y `op.drop_table` **no** borra los
#: tipos que una columna creo implicitamente. El resultado es que un
#: `downgrade base` dejaba los 22 tipos vivos y el siguiente `upgrade` reventaba
#: con `type "job_kind" already exists`. El sintoma es desconcertante porque el
#: rollback informaba exito.
#:
#: Asi que los enums se tratan como objetos de primer clase: se garantiza que no queden
#: de una corrida anterior antes de empezar, y se tiran al final del `downgrade`.
#: `IF EXISTS` y `CASCADE` hacen que las dos puntas sean idempotentes.
ENUM_TYPES: tuple[str, ...] = (
    "audit_actor_type",
    "block_kind",
    "booking_event_type",
    "booking_source",
    "booking_status",
    "business_status",
    "business_user_role",
    "job_kind",
    "job_status",
    "media_kind",
    "media_status",
    "membership_status",
    "notification_channel",
    "notification_kind",
    "notification_status",
    "platform_role",
    "template_status",
    "time_off_kind",
    "time_off_status",
    "webhook_provider",
    "webhook_status",
    "whatsapp_connection_status",
)


def _drop_enum_types() -> None:
    for enum_type in ENUM_TYPES:
        op.execute(f'DROP TYPE IF EXISTS "{enum_type}" CASCADE')


def upgrade() -> None:
    # Limpieza previa: si una corrida anterior fallo a mitad de camino, quedan
    # enums y tablas colgando que hacen fallar este upgrade por el motivo equivocado.
    _drop_enum_types()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("locked_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "response_status IS NULL OR (response_status >= 100 AND response_status < 600)",
            name=op.f("ck_idempotency_keys_response_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "business_id", "scope", "key", name="uq_idempotency_keys_business_id_scope_key"
        ),
        sa.UniqueConstraint(
            "business_id", "scope", "key", name="uq_idempotency_keys_business_id_scope_key"
        ),
        sa.UniqueConstraint("id", "business_id", name="uq_idempotency_keys_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_idempotency_keys_business_id"), "idempotency_keys", ["business_id"], unique=False
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("reminder", "whatsapp_outbound", "webhook", "media", "report", name="job_kind"),
            nullable=False,
        ),
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "run_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", "failed", "dead", name="job_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("locked_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_key", name="uq_jobs_dedupe_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_jobs_business_id"), "jobs", ["business_id"], unique=False)
    op.create_index(
        "ix_jobs_ready",
        "jobs",
        ["run_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "media",
        sa.Column(
            "kind",
            sa.Enum("logo", "cover", "professional_photo", name="media_kind"),
            nullable=False,
        ),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "ready", "failed", name="media_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(width IS NULL) = (height IS NULL)", name=op.f("ck_media_dimensions_paired")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_media_size_bytes_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("id", "business_id", name="uq_media_id_business_key"),
        sa.UniqueConstraint("object_key", name=op.f("uq_media_object_key")),
        info={"rls": True},
    )
    op.create_index(op.f("ix_media_business_id"), "media", ["business_id"], unique=False)
    op.create_table(
        "platform_users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "support", "admin", name="platform_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_users")),
    )
    op.create_index("ix_platform_users_email", "platform_users", ["email"], unique=True)
    op.create_table(
        "rate_limit_buckets",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("window_start", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "hits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("count >= 0", name=op.f("ck_rate_limit_buckets_count_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_buckets")),
        sa.UniqueConstraint("key", "window_start", name="uq_rate_limit_buckets_key_window_start"),
    )
    op.create_index(op.f("ix_rate_limit_buckets_key"), "rate_limit_buckets", ["key"], unique=False)
    op.create_table(
        "slug_reservations",
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slug_reservations")),
        sa.UniqueConstraint("slug", name=op.f("uq_slug_reservations_slug")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("provider", sa.Enum("meta", name="webhook_provider"), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("received", "processed", "failed", "ignored", name="webhook_status"),
            server_default=sa.text("'received'"),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint(
            "provider", "external_id", name="uq_webhook_events_provider_external_id"
        ),
    )
    op.create_table(
        "businesses",
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "timezone",
            sa.Text(),
            server_default=sa.text("'America/Argentina/Buenos_Aires'"),
            nullable=False,
        ),
        sa.Column("locale", sa.Text(), server_default=sa.text("'es-AR'"), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'ARS'"), nullable=False),
        sa.Column(
            "slot_interval_minutes", sa.Integer(), server_default=sa.text("15"), nullable=False
        ),
        sa.Column("min_lead_minutes", sa.Integer(), server_default=sa.text("60"), nullable=False),
        sa.Column("max_advance_days", sa.Integer(), server_default=sa.text("60"), nullable=False),
        sa.Column(
            "cancellation_window_minutes",
            sa.Integer(),
            server_default=sa.text("120"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "trial", "suspended", name="business_status"),
            server_default=sa.text("'trial'"),
            nullable=False,
        ),
        sa.Column("phone_e164", sa.Text(), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("brand_color", sa.Text(), nullable=True),
        sa.Column("logo_media_id", sa.Uuid(), nullable=True),
        sa.Column("cover_media_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cancellation_window_minutes >= 0",
            name=op.f("ck_businesses_cancellation_window_non_negative"),
        ),
        sa.CheckConstraint(
            "max_advance_days > 0", name=op.f("ck_businesses_max_advance_days_positive")
        ),
        sa.CheckConstraint(
            "min_lead_minutes >= 0", name=op.f("ck_businesses_min_lead_non_negative")
        ),
        sa.CheckConstraint(
            "slot_interval_minutes > 0", name=op.f("ck_businesses_slot_interval_positive")
        ),
        sa.ForeignKeyConstraint(
            ["cover_media_id"],
            ["media.id"],
            name="fk_businesses_cover_media_id_media",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["logo_media_id"],
            ["media.id"],
            name="fk_businesses_logo_media_id_media",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("slug", name=op.f("uq_businesses_slug")),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "actor_type",
            sa.Enum("user", "customer", "system", name="audit_actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_audit_log_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("id", "business_id", name="uq_audit_log_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_audit_log_business_id"), "audit_log", ["business_id"], unique=False)
    op.create_table(
        "business_exceptions",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_business_exceptions_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_exceptions")),
        sa.UniqueConstraint(
            "business_id", "local_date", name="uq_business_exceptions_business_id_local_date"
        ),
        sa.UniqueConstraint("id", "business_id", name="uq_business_exceptions_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_business_exceptions_business_id"),
        "business_exceptions",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "business_hours",
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("window_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("is_open", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_open = false OR end_time > start_time",
            name=op.f("ck_business_hours_end_after_start"),
        ),
        sa.CheckConstraint(
            "is_open = false OR end_time IS NOT NULL",
            name=op.f("ck_business_hours_open_window_has_end"),
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_business_hours_weekday_in_range")
        ),
        sa.CheckConstraint(
            "window_index >= 0", name=op.f("ck_business_hours_window_index_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_business_hours_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_hours")),
        sa.UniqueConstraint(
            "business_id",
            "weekday",
            "window_index",
            name="uq_business_hours_business_id_weekday_window_index",
        ),
        sa.UniqueConstraint("id", "business_id", name="uq_business_hours_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_business_hours_business_id"), "business_hours", ["business_id"], unique=False
    )
    op.create_table(
        "business_users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("admin", "staff", name="business_user_role"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "invited", "disabled", name="membership_status"),
            server_default=sa.text("'invited'"),
            nullable=False,
        ),
        sa.Column("last_login_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("invited_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_business_users_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_users")),
        sa.UniqueConstraint("id", "business_id", name="uq_business_users_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_business_users_business_id"), "business_users", ["business_id"], unique=False
    )
    op.create_index(
        "uq_business_users_business_id_email",
        "business_users",
        ["business_id", "email"],
        unique=True,
    )
    op.create_table(
        "customers",
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("phone_e164", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_opted_out", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "marketing_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_booking_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_opted_out = false OR marketing_opt_in = false",
            name=op.f("ck_customers_opt_out_clears_marketing"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_customers_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("id", "business_id", name="uq_customers_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_customers_business_id"), "customers", ["business_id"], unique=False)
    op.create_index(
        "uq_customers_business_id_phone", "customers", ["business_id", "phone_e164"], unique=True
    )
    op.create_table(
        "holidays",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_holidays_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("business_id", "local_date", name="uq_holidays_business_id_local_date"),
        sa.UniqueConstraint("id", "business_id", name="uq_holidays_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_holidays_business_id"), "holidays", ["business_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "price", sa.Numeric(precision=12, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("archived_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_services_duration_positive")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_services_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_services_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("id", "business_id", name="uq_services_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_services_business_id"), "services", ["business_id"], unique=False)
    op.create_table(
        "whatsapp_connections",
        sa.Column("phone_number_id", sa.String(length=64), nullable=False),
        sa.Column("waba_id", sa.String(length=64), nullable=False),
        sa.Column("display_phone", sa.String(length=32), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("app_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("messaging_limit_tier", sa.String(length=64), nullable=True),
        sa.Column("quality_rating", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "expired",
                "revoked",
                "error",
                name="whatsapp_connection_status",
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("connected_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("token_expires_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_whatsapp_connections_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_connections")),
        sa.UniqueConstraint("business_id", name="uq_whatsapp_connections_business_id"),
        sa.UniqueConstraint("id", "business_id", name="uq_whatsapp_connections_id_business_key"),
        sa.UniqueConstraint("waba_id", name="uq_whatsapp_connections_waba_id"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_whatsapp_connections_business_id"),
        "whatsapp_connections",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "whatsapp_templates",
        sa.Column("business_id", sa.Uuid(), nullable=True),
        sa.Column("meta_name", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum("approved", "pending", "rejected", name="template_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name="fk_whatsapp_templates_business_id_businesses",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_templates")),
        sa.UniqueConstraint(
            "business_id",
            "meta_name",
            "language",
            name="uq_whatsapp_templates_business_id_meta_name_language",
        ),
        sa.UniqueConstraint("id", "business_id", name="uq_whatsapp_templates_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_whatsapp_templates_business_id"),
        "whatsapp_templates",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "business_exception_windows",
        sa.Column("exception_id", sa.Uuid(), nullable=False),
        sa.Column("window_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_business_exception_windows_end_after_start")
        ),
        sa.CheckConstraint(
            "window_index >= 0",
            name=op.f("ck_business_exception_windows_window_index_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["exception_id", "business_id"],
            ["business_exceptions.id", "business_exceptions.business_id"],
            name="fk_business_exception_windows_exception",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_exception_windows")),
        sa.UniqueConstraint(
            "exception_id",
            "window_index",
            name="uq_business_exception_windows_exception_id_window_index",
        ),
        sa.UniqueConstraint(
            "id", "business_id", name="uq_business_exception_windows_id_business_key"
        ),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_business_exception_windows_business_id"),
        "business_exception_windows",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "professionals",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("archived_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(user_id IS NULL) OR (archived_at IS NULL)",
            name=op.f("ck_professionals_login_requires_not_archived"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "business_id"],
            ["business_users.id", "business_users.business_id"],
            name="fk_professionals_user_id_business_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professionals")),
        sa.UniqueConstraint("id", "business_id", name="uq_professionals_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_professionals_business_id"), "professionals", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_professionals_user_id"), "professionals", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("platform_user_id", sa.Uuid(), nullable=True),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("last_used_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_refresh_tokens_expires_after_creation")
        ),
        sa.CheckConstraint(
            "num_nonnulls(user_id, platform_user_id) = 1",
            name=op.f("ck_refresh_tokens_exactly_one_principal"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_refresh_tokens_platform_user_id_platform_users",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name="fk_refresh_tokens_replaced_by_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["business_users.id"],
            name="fk_refresh_tokens_user_id_business_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"], unique=False)
    op.create_index(
        op.f("ix_refresh_tokens_platform_user_id"),
        "refresh_tokens",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "blocks",
        sa.Column("professional_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind", sa.Enum("unpaid", "private", "blocked", name="block_kind"), nullable=False
        ),
        sa.Column("starts_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("ends_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("occupied_from", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("occupied_to", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(occupied_from IS NULL) = (occupied_to IS NULL)",
            name=op.f("ck_blocks_occupied_range_paired"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_blocks_ends_after_starts")),
        sa.CheckConstraint(
            "occupied_from IS NULL OR occupied_to > occupied_from",
            name=op.f("ck_blocks_occupied_to_after_from"),
        ),
        sa.ForeignKeyConstraint(
            ["professional_id", "business_id"],
            ["professionals.id", "professionals.business_id"],
            name="fk_blocks_professional",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint("id", "business_id", name="uq_blocks_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_blocks_business_id"), "blocks", ["business_id"], unique=False)
    op.create_index(
        "ix_blocks_occupied_range",
        "blocks",
        ["business_id", "occupied_from", "occupied_to"],
        unique=False,
    )
    op.create_index(op.f("ix_blocks_professional_id"), "blocks", ["professional_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_hold",
                "confirmed",
                "cancelled",
                "completed",
                "no_show",
                name="booking_status",
            ),
            server_default=sa.text("'pending_hold'"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("public", "admin", "walkin", name="booking_source"),
            server_default=sa.text("'public'"),
            nullable=False,
        ),
        sa.Column("starts_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("ends_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("occupied_from", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("occupied_to", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("price_snapshot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("secure_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("token_rotated_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rescheduled_from_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "confirmed_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cancelled_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("professional_id"), "="),
            (sa.text("tstzrange(occupied_from, occupied_to, '[)')"), "&&"),
            where=sa.text("status IN ('confirmed', 'pending_hold')"),
            using="gist",
            name="no_overlap",
        ),
        sa.CheckConstraint(
            "(status = 'cancelled') = (cancelled_at IS NOT NULL)",
            name=op.f("ck_bookings_cancelled_flag_matches_timestamp"),
        ),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_bookings_duration_positive")),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_bookings_ends_after_starts")),
        sa.CheckConstraint(
            "occupied_from <= starts_at", name=op.f("ck_bookings_occupied_starts_before_service")
        ),
        sa.CheckConstraint(
            "occupied_to >= ends_at", name=op.f("ck_bookings_occupied_ends_after_service")
        ),
        sa.CheckConstraint(
            "price_snapshot >= 0", name=op.f("ck_bookings_price_snapshot_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["business_users.id"],
            name="fk_bookings_created_by_user_id_business_users",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "business_id"],
            ["customers.id", "customers.business_id"],
            name="fk_bookings_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["professional_id", "business_id"],
            ["professionals.id", "professionals.business_id"],
            name="fk_bookings_professional",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rescheduled_from_id", "business_id"],
            ["bookings.id", "bookings.business_id"],
            name="fk_bookings_rescheduled_from",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id", "business_id"],
            ["services.id", "services.business_id"],
            name="fk_bookings_service",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("id", "business_id", name="uq_bookings_id_business_key"),
        sa.UniqueConstraint("secure_token_hash", name=op.f("uq_bookings_secure_token_hash")),
        info={"rls": True},
    )
    op.create_index(op.f("ix_bookings_business_id"), "bookings", ["business_id"], unique=False)
    op.create_index(
        "ix_bookings_business_id_local_date",
        "bookings",
        ["business_id", "local_date"],
        unique=False,
    )
    op.create_index(
        "ix_bookings_professional_id_starts_at",
        "bookings",
        ["professional_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_rescheduled_from_id"), "bookings", ["rescheduled_from_id"], unique=False
    )
    op.create_table(
        "professional_schedules",
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("window_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_override", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_professional_schedules_end_after_start")
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_professional_schedules_weekday_in_range")
        ),
        sa.CheckConstraint(
            "window_index >= 0", name=op.f("ck_professional_schedules_window_index_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["professional_id", "business_id"],
            ["professionals.id", "professionals.business_id"],
            name="fk_professional_schedules_professional",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_schedules")),
        sa.UniqueConstraint("id", "business_id", name="uq_professional_schedules_id_business_key"),
        sa.UniqueConstraint(
            "professional_id",
            "weekday",
            "window_index",
            name="uq_professional_schedules_professional_id_weekday_window_index",
        ),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_professional_schedules_business_id"),
        "professional_schedules",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "professional_services",
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("custom_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("custom_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "custom_duration_minutes IS NULL OR custom_duration_minutes > 0",
            name=op.f("ck_professional_services_custom_duration_positive"),
        ),
        sa.CheckConstraint(
            "custom_price IS NULL OR custom_price >= 0",
            name=op.f("ck_professional_services_custom_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["professional_id", "business_id"],
            ["professionals.id", "professionals.business_id"],
            name="fk_professional_services_professional",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id", "business_id"],
            ["services.id", "services.business_id"],
            name="fk_professional_services_service",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("professional_id", "service_id", name="pk_professional_services"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_professional_services_business_id"),
        "professional_services",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "time_off",
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("vacation", "leave", "sick", "absence", name="time_off_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="time_off_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("starts_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("ends_at", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_time_off_ends_after_starts")),
        sa.ForeignKeyConstraint(
            ["professional_id", "business_id"],
            ["professionals.id", "professionals.business_id"],
            name="fk_time_off_professional",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_off")),
        sa.UniqueConstraint("id", "business_id", name="uq_time_off_id_business_key"),
        info={"rls": True},
    )
    op.create_index(op.f("ix_time_off_business_id"), "time_off", ["business_id"], unique=False)
    op.create_table(
        "booking_events",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "created",
                "cancelled",
                "rescheduled",
                "rescheduled_to",
                "completed",
                "no_show",
                "walkin_registered",
                "token_rotated",
                name="booking_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum("user", "customer", "system", name="audit_actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("from_starts_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("to_starts_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id", "business_id"],
            ["bookings.id", "bookings.business_id"],
            name="fk_booking_events_booking",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_events")),
        sa.UniqueConstraint("id", "business_id", name="uq_booking_events_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        "ix_booking_events_booking_id_created_at",
        "booking_events",
        ["booking_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_booking_events_business_id"), "booking_events", ["business_id"], unique=False
    )
    op.create_table(
        "notification_requests",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "booking_confirmed",
                "booking_cancelled",
                "booking_rescheduled",
                "reminder_24h",
                "reminder_2h",
                "reminder_1h",
                "professional_new_booking",
                "professional_booking_cancelled",
                name="notification_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "sms", "email", name="notification_channel"),
            server_default=sa.text("'whatsapp'"),
            nullable=False,
        ),
        sa.Column("scheduled_for", app.db.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "delivered",
                "failed",
                "skipped",
                "cancelled",
                name="notification_status",
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("template_name", sa.String(length=255), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("sent_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", app.db.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.UtcDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_notification_requests_attempts_non_negative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_notification_requests_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id", "business_id"],
            ["bookings.id", "bookings.business_id"],
            name="fk_notification_requests_booking",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "business_id"],
            ["customers.id", "customers.business_id"],
            name="fk_notification_requests_customer",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_requests")),
        sa.UniqueConstraint("booking_id", "kind", name="uq_notification_requests_booking_id_kind"),
        sa.UniqueConstraint("id", "business_id", name="uq_notification_requests_id_business_key"),
        info={"rls": True},
    )
    op.create_index(
        op.f("ix_notification_requests_business_id"),
        "notification_requests",
        ["business_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_requests_business_id"), table_name="notification_requests")
    op.drop_table("notification_requests")
    op.drop_index(op.f("ix_booking_events_business_id"), table_name="booking_events")
    op.drop_index("ix_booking_events_booking_id_created_at", table_name="booking_events")
    op.drop_table("booking_events")
    op.drop_index(op.f("ix_time_off_business_id"), table_name="time_off")
    op.drop_table("time_off")
    op.drop_index(op.f("ix_professional_services_business_id"), table_name="professional_services")
    op.drop_table("professional_services")
    op.drop_index(
        op.f("ix_professional_schedules_business_id"), table_name="professional_schedules"
    )
    op.drop_table("professional_schedules")
    op.drop_index(op.f("ix_bookings_rescheduled_from_id"), table_name="bookings")
    op.drop_index("ix_bookings_professional_id_starts_at", table_name="bookings")
    op.drop_index("ix_bookings_business_id_local_date", table_name="bookings")
    op.drop_index(op.f("ix_bookings_business_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_blocks_professional_id"), table_name="blocks")
    op.drop_index("ix_blocks_occupied_range", table_name="blocks")
    op.drop_index(op.f("ix_blocks_business_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_platform_user_id"), table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_professionals_user_id"), table_name="professionals")
    op.drop_index(op.f("ix_professionals_business_id"), table_name="professionals")
    op.drop_table("professionals")
    op.drop_index(
        op.f("ix_business_exception_windows_business_id"), table_name="business_exception_windows"
    )
    op.drop_table("business_exception_windows")
    op.drop_index(op.f("ix_whatsapp_templates_business_id"), table_name="whatsapp_templates")
    op.drop_table("whatsapp_templates")
    op.drop_index(op.f("ix_whatsapp_connections_business_id"), table_name="whatsapp_connections")
    op.drop_table("whatsapp_connections")
    op.drop_index(op.f("ix_services_business_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_holidays_business_id"), table_name="holidays")
    op.drop_table("holidays")
    op.drop_index("uq_customers_business_id_phone", table_name="customers")
    op.drop_index(op.f("ix_customers_business_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index("uq_business_users_business_id_email", table_name="business_users")
    op.drop_index(op.f("ix_business_users_business_id"), table_name="business_users")
    op.drop_table("business_users")
    op.drop_index(op.f("ix_business_hours_business_id"), table_name="business_hours")
    op.drop_table("business_hours")
    op.drop_index(op.f("ix_business_exceptions_business_id"), table_name="business_exceptions")
    op.drop_table("business_exceptions")
    op.drop_index(op.f("ix_audit_log_business_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("businesses")
    op.drop_table("webhook_events")
    op.drop_table("slug_reservations")
    op.drop_index(op.f("ix_rate_limit_buckets_key"), table_name="rate_limit_buckets")
    op.drop_table("rate_limit_buckets")
    op.drop_index("ix_platform_users_email", table_name="platform_users")
    op.drop_table("platform_users")
    op.drop_index(op.f("ix_media_business_id"), table_name="media")
    op.drop_table("media")
    op.drop_index(
        "ix_jobs_ready", table_name="jobs", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_index(op.f("ix_jobs_business_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_business_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
    # Los enums se van al final y no antes: si se tiraran primero, las tablas que
    # los usan todavia estarian en pie y el `DROP TYPE` fallaria por dependencias.
    _drop_enum_types()
